---
title: "Overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
library(nonparam)
```



### wilcoxontest
Example:
```{r}
(w1 <- wilcoxon(c(1,2,3), c(6,5,4)))
w21 <- rnorm(15, 0, 1); w22 <- rnorm(15, 5, 1)
(w2 <- wilcoxon(w21, w22))
```



Comparison:
```{r}
# built-in
wilcox.test(c(1,2,3), c(6,5,4))
wilcox.test(w21, w22)
```



### kendalltest
Example:
```{r}
#kendall()
```



Comparison:
```{r}
# built-in
#cor.test(x = X, y = Y, method = "kendall", conf.level = 0.95, alternative = "greater")
```


### spearmantest
Example:
```{r}
library(SuppDists)
spearman(c(1,2,3), c(6,5,4))
spearman(w21, w22)
```



Comparison:
```{r}
# built-in
cor.test(c(1,2,3), c(6,5,4), method = "spearman", alternative = "greater")
cor.test(x = w21, y = w22, method = "spearman", alternative = "greater")
```








